### ISSUE TITLE
docs: create README

### ISSUE THREAD

**Issue by gdcmarinho** [stylizedjs/stylized#3]
Create the project README including:
- [x] Logo
- [x] Badges
- [x] Features
- [x] Prerequisites
- [x] Installation tutorial
- [x] Usage tutorial
- [x] Contributing guideline reference
- [x] FAQ
- [x] LICENSE information

**Comment by gabrielcmarinho** [comment]
initial commit 6e712dfe3547c76e81309754f4314d634d774ccc
