### ISSUE TITLE
publish on NPM

### ISSUE THREAD

**Issue by gdcmarinho** [stylizedjs/stylized#6]
Final alpha beta published on [NPM](https://www.npmjs.com/).

**Comment by gabrielcmarinho** [comment]
resolved https://github.com/gabrielcmarinho/stylized/commit/478a13aea9ce49211f8d5fba5005d1865e65dd18

First version of Stylized published at https://www.npmjs.com/package/stylizedcss ✨

**Comment by gdcmarinho** [comment]
Republished Stylized at https://www.npmjs.com/package/stylizedjs ✨
